<a href="https://colab.research.google.com/github/KurumiZaphkielll/MikuNakano.github.io/blob/main/udmy3_Dataframe_from_Dictionary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creación de DataFrames a partir de un diccionario

En este programa se utiliza un diccionario para crear un DataFrame con información de nombre, edad y género. Además, se asignan índices personalizados a cada registro para organizar mejor los datos.

##Markdown

## 1. Importación de Pandas

Se importa la librería **Pandas**, necesaria para crear y trabajar con DataFrames en Python.

In [ ]:
import pandas as pd

## 2. Creación del diccionario

Se crea el diccionario `data` con tres categorías de información: nombre (`name`), edad (`age`) y género (`gender`). Cada clave contiene una lista de valores que posteriormente se utilizará para construir el DataFrame.

In [ ]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

## 3. Creación del DataFrame

Se utiliza `pd.DataFrame(data)` para convertir el diccionario `data` en un DataFrame, organizando cada clave como una columna y sus valores como filas.

In [ ]:
pd.DataFrame(data)

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

## 4. Asignación de índices personalizados

Se utiliza el parámetro `index` para asignar identificadores personalizados a cada fila del DataFrame. En este caso, las filas se identifican como `Kid1`, `Kid2` y `Kid3`.

In [ ]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male